### ISSUE TITLE
Add HEX_API_KEY to Travis

### ISSUE THREAD

**Issue by radditude** [revelrylabs/phoenix_harmonium#41]
Still a few steps left to finish setting up the auto-publish on tags functionality in Travis:

1. package owner needs to run `mix hex.user key generate` locally
2. then set that value as `HEX_API_KEY` in Travis

**Comment by jwietelmann** [comment]
done

**Comment by radditude** [comment]
I did a dumb thing just now when switching this over to OpenCov - I accidentally hit the delete button on the `HEX_API_KEY` env var in Travis 🤦‍♂️ Reopening this for next time we need to publish a new version.

**Comment by grossvogel** [comment]
This was updated when `2.1.0` was shipped: https://travis-ci.com/revelrylabs/phoenix_harmonium/builds/121432051
